class_name StarSystemData
extends RefCounted

# =============================================================================
# Star System Data - Describes a complete star system
# Generated by SystemGenerator, consumed by EntityRegistry + StellarMap
# =============================================================================

var system_name: String = ""
var seed_value: int = 0

# Star info
var star_name: String = ""
var star_spectral_class: String = ""  # O, B, A, F, G, K, M
var star_temperature: float = 5778.0   # Kelvin
var star_radius: float = 696340000.0   # meters (Sol default)
var star_color: Color = Color.WHITE
var star_luminosity: float = 1.0

# Planets: array of dictionaries
# Each: {
#   "name": String, "type": String, "orbital_radius": float (meters),
#   "orbital_period": float (seconds), "orbital_angle": float,
#   "radius": float (meters), "color": Color,
#   "has_rings": bool, "mass": float
# }
var planets: Array[Dictionary] = []

# Asteroid belts: array of dictionaries
# Each: { "name": String, "orbital_radius": float, "width": float }
var asteroid_belts: Array[Dictionary] = []

# Stations: array of dictionaries
# Each: { "name": String, "orbital_radius": float, "orbital_parent": String, "orbital_period": float }
var stations: Array[Dictionary] = []

# Jump gates: array of dictionaries
# Each: { "name": String, "target_system_id": int, "target_system_name": String,
#          "pos_x": float, "pos_y": float, "pos_z": float }
var jump_gates: Array[Dictionary] = []
