class_name StarSystemData
extends Resource

# =============================================================================
# Star System Data — Full description of a star system
# Resource: editable in Godot inspector, saveable as .tres for custom systems.
# Generated by SystemGenerator, consumed by SystemTransition + EntityRegistry.
# =============================================================================

@export_group("Identity")
@export var system_name: String = ""
@export var seed_value: int = 0

@export_group("Star")
@export var star_name: String = ""
@export var star_spectral_class: String = "G"
@export var star_temperature: float = 5778.0
@export var star_radius: float = 696340.0
@export var star_color: Color = Color.WHITE
@export var star_luminosity: float = 1.0

@export_group("Contents")
@export var planets: Array[PlanetData] = []
@export var stations: Array[StationData] = []
@export var asteroid_belts: Array[AsteroidBeltData] = []
@export var jump_gates: Array[JumpGateData] = []

@export_group("Environment Override")
## Optional: assign a custom SystemEnvironmentData to override the auto-generated one.
@export var environment_override: SystemEnvironmentData = null
